services:

  appDb:
    image: bitnami/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: alta
    ports: 
      - 3306:3306
    volumes:
      # - './data:/bitnami/mysql/data'
      - './initdb:/docker-entrypoint-initdb.d'
    healthcheck:
      test: ["CMD", "mysql", "-u", "root",  "-ptoor", "-e", "show schemas"]
      interval: 10s 

  app:
    build: .
    restart: always
    depends_on:
      appDb:
        condition: service_healthy
    environment:
      HTTP_PORT: 8080
      CONNECTION_STRING: root:toor@tcp(appDb:3306)/alta?charset=utf8&parseTime=True&loc=Local
      STORAGE: db
    ports:
      - 8080:8080

  adminer:
    image: adminer
    restart: always
    ports: # host:container
      - 8081:8080